ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone VARCHAR(20),
    ADD COLUMN IF NOT EXISTS gender VARCHAR(10),
    ADD COLUMN IF NOT EXISTS date_of_birth DATE,
    ADD COLUMN IF NOT EXISTS is_account_non_locked BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS user_type VARCHAR(20) DEFAULT 'USER';

ALTER TABLE employees
    DROP COLUMN IF EXISTS first_name,
    DROP COLUMN IF EXISTS last_name,
    DROP COLUMN IF EXISTS email,
    DROP COLUMN IF EXISTS date_of_birth,
    DROP COLUMN IF EXISTS gender
